### ISSUE TITLE
Add "advertise_connector" as an option in the configuration file

### ISSUE THREAD

**Issue by mooangus** [tsujamin/hass-addons#103]
**Is your feature request related to a problem? Please describe.**
Tailscale has added an option to advertise connectors.  This has not yet been added an as option.

**Describe the solution you'd like**
The ability to add "advertise_connector" in the config file and pass the option when Tailscale runs.

**Describe alternatives you've considered**
I am unsure if there is a good alternative

**Additional context**
NA

Thanks for the hard work keeping the add-on up to date.  It's much appreciated!

-Chris

**Comment by mooangus** [comment]
Pull request with proposed update:

https://github.com/tsujamin/hass-addons/pull/104

**Comment by bslatyer** [comment]
Hey @mooangus,

LGTM!

I'll let the final say come from @tsujamin :)

**Comment by tsujamin** [comment]
Yup lgtm too - have merged and will quickly cut a point release. Thanks for the contribution!

**Comment by tsujamin** [comment]
Should be in v1.56.1.1 - just refresh your hass addons and apply the update, thanks again!
