### ISSUE TITLE
upgrade to latest version error

### ISSUE THREAD

**Issue by drorengel** [tsujamin/hass-addons#117]
**Describe the bug**
I've been trying to upgrade the version for the past few releases and get the same error. I also tried to uninstall the add on and when I try to install it again, I get the same error

The command '/bin/bash -o pipefail -c apt install -y wget iptables iproute2 procps iputils-ping' returned a non-zero code: 100

**To Reproduce**
1. Go to Addon page
2. Click on update

 - Home Assistant/Supervisor Versions:
 - Core
2024.5.3
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1

**Comment by bslatyer** [comment]
Hey @drorengel,

What hardware and architecture is this being run on?

E.g. Raspberry Pi 5 (ARM64)

Thanks,

Braeden

**Comment by drorengel** [comment]
Raspberry Pi 4 2GB. As a reference, this version is working fine
https://github.com/hassio-addons/addon-tailscale/tree/v0.18.0

**Comment by bslatyer** [comment]
Hmm, that's very strange.

Two days ago, I tested the most recent version (v1.66.1) on an RPi4, and it didn't have this issue.

I'll do some testing and get back to you on this one.

**Comment by bslatyer** [comment]
Heya,

I tested the latest versions, v1.66.1 and v1.66.3, and they seem to work fine on both RPi4 and RPi5.

Can you provide any logs or anything else that might help?

Thanks,

Braeden
