### ISSUE TITLE
1.66.4 - addon unable to start

### ISSUE THREAD

**Issue by ga2pegw** [tsujamin/hass-addons#120]
**Describe the bug**
After updating from 1.66.3, the addon begins startup but eventually errors out with the below. Reverting back to 1.66.3 works

Snippet from log:

```
*2024/05/31 08:59:36 health("overall"): ok
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:

	tailscale up --advertise-routes=10.0.15.0/24,10.0.33.0/24 --auth-key=tskey-REDACTED --hostname=home-assistant --stateful-filtering
``` 

*To Reproduce**
1. Go to 'Settings>Add-ons>Tailscale'
2. Click on 'Update'
3. Check Logs
5. Addon stops 

**Expected behavior**
Addon to start and stay running

**Desktop (please complete the following information):**
 - Plugin Version: 1.66.4
 - Home Assistant/Supervisor Versions: Home Assistant 2024.5.5 / Supervisor 2024.05.1

**Comment by magkopian** [comment]
I had the same problem. You just need to enable the `reset` option from the configuration and restart the add-on. After that you should be able disable it again, restart the add-on, and everything should be working.

**Comment by ga2pegw** [comment]
You're correct - setting the reset option worked. Thanks!
