### ISSUE TITLE
How to pass the parameter "--accept-routes" to the tailscale binary?

### ISSUE THREAD

**Issue by ovizii** [tsujamin/hass-addons#13]
Could you please create an option for that or a checkbox? Its described here https://tailscale.com/kb/1019/subnets/  that you need this option if you would like a linux tailscale instance to actually use advertised routes by other tailscale instances.

**Comment by tsujamin** [comment]
Yep - will push it in `1.10.0.1` this evening, but I'm not 100% sure how it'll play with hass so would appreciate some feedback based on your experience if that's all good?

**Comment by tsujamin** [comment]
reload your repositories and give it a whirl! if it works as expected I'll close out this issue

**Comment by ovizii** [comment]
thanks, that was very quick :-) 

I'll close this issue as I can't test it right now. Believe it or not, I forgot my use case. I was playing around with 2 instances of Home Assistant and 2 web cams, one attached to each of the HA instances and wanted to interconnect them all with 1 shinobi instance when I realized I'd need "--accept-routes" on the remote HA to get to the shinobi instance but I didn't write down the whole "plan". 

Go ahead, have a good laugh, I deserve it.

**Comment by tsujamin** [comment]
all good! fortuitous timing more than anything.

 I hadn't thought of that usecase before, but super cool idea (effectively mesh-networking hass boxes)

✌️
