### ISSUE TITLE
Cannot upgrade Tailscale Addon to 1.76.6

### ISSUE THREAD

**Issue by askjano** [tsujamin/hass-addons#132]
**Describe the bug**
I currently have Tailscale Addon v1.76.1.0 installed. I am presented with the option to upgrade to 1.76.6.0. Update fails with the following error:

The command '/bin/bash -o pipefail -c apt install -y wget iptables iproute2 procps iputils-ping' returned a non-zero code: 100

Logs provide no info since it seems they are only logging the running Tailscale process and not the install process

**To Reproduce**
Pressing the update button within the addon section or via the general HA update section. 

**Expected behavior**
The expected behavior is for the update to complete successfully. 

**Desktop (please complete the following information):**
 - Plugin Version:  current version 1.76.1
 - Home Assistant/Supervisor Versions: 
 Version 	core-2024.11.0
Installation type 	Home Assistant OS
Host operating system 	Home Assistant OS 13.2
Update channel 	stable
Supervisor version 	supervisor-2024.11.2

**Additional context**
Not sure if the recent HA 2024.11 release caused the issue as I had already upgraded prior to being notified of the Tailscale update.

**Comment by benjaminroberts10** [comment]
Hey mate - Sorry to be a pain, but can you try again in a couple of days? Historically where we've seen this issue it's been to do with your local Debian mirror being out-of-sync causing package update errors.

Write back next week if you've still got the issue and I can take a look.

**Comment by benjaminroberts10** [comment]
https://github.com/tsujamin/hass-addons/issues/87#issuecomment-1684240329 there's a couple tickets for a similar issue, this comment might help in the interim :)

**Comment by askjano** [comment]
i tried again this morning and still nothing. i followed the steps from the comment you posted but now after removing the repo updating and adding the repo back i still get the same message. i will try again next week and see if anything changes. thank you.

**Comment by tsujamin** [comment]
Thanks mate - let me know!

**Comment by askjano** [comment]
i ended up using the ha addon for tailscale

https://github.com/hassio-addons/addon-tailscale

its been working and i was able to update to the most current tailscale release

**Comment by bslatyer** [comment]
Too easy!

I'll close this off now.
