### ISSUE TITLE
Failed to install on raspberry pi 4

### ISSUE THREAD

**Issue by sharathbk1912** [tsujamin/hass-addons#16]
Hi 

This addon Is erroring as it cant access the package tar  

![image](https://user-images.githubusercontent.com/79350776/127106670-0da27326-c207-4d98-8af3-c378df23c785.png)

Its looking for armv7 i.e arm package which is present still it doesnt pick .

I am able to reach this address pkgs.tailscale.com

![image](https://user-images.githubusercontent.com/79350776/127106750-631bce1d-3d51-4062-960c-a8fd245c9c0c.png)

am i missing something ? 

Also can u add a print above this statement . To make sure expected link is generated 

![image](https://user-images.githubusercontent.com/79350776/127109000-514c8bd3-c9ea-4e31-bb3b-af7b6ae00e77.png)

Tried manually in the docker container to make sure this is accessible 

![image](https://user-images.githubusercontent.com/79350776/127112174-4272c5ce-bc15-4367-b320-badf5ec818c7.png)

Thanks and Regards
Sharath

**Comment by tsujamin** [comment]
Hey mate, sorry the add-on is causing issues for you!

The `install.sh` script downloads tailscale_VER_arm.tgz for both armhf and armv7 so the URL is fine. I think the actual issue is the container not being able to resolve or connect to pkgs.tailscale.com (i.e. the "bad address" error at the end).

This seems similar to https://github.com/tsujamin/hass-addons/issues/11. Could you quickly confirm the following for me?

  * What kind of Home Assistant installation are you running? (HassOS/hand built etc)
  * Could you retry installing the addon one more time (ideally 24h after the last attempt) just to confirm its not an intermittent fault
  * Can you wget/curl pkgs.tailscale.com from within any other Home Assistant containers that are running?
  * Do you have IPv6 connectivity from the network your Home Assistant install is on?

There's a fork of this repo with some additional testing and logging @ https://github.com/tsujamin/tailscale-badaddr-test if you want to try that and report back.

**Comment by sharathbk1912** [comment]
Hi 

What kind of Home Assistant installation are you running? (HassOS/hand built etc)
**supervised hass io**
Could you retry installing the addon one more time (ideally 24h after the last attempt) just to confirm its not an intermittent fault
**this i have done did not help -> tried in gaps of weeks also with restart**
Can you wget/curl pkgs.tailscale.com from within any other Home Assistant containers that are running?
**from within any other home assistant container also it work** 
Do you have IPv6 connectivity from the network your Home Assistant install is on?
**no there is no IPv6 connectivity from my ISP**

Output of the other test repository

Step 1/18 : ARG BUILD_ARCH
Step 2/18 : FROM homeassistant/${BUILD_ARCH}-base:latest
 ---> 564b1f71f9e5
Step 3/18 : ARG BUILD_ARCH
 ---> Using cache
 ---> 2ee8490de1e9
Step 4/18 : ARG TAILSCALE_VERSION="1.8.3"
 ---> Running in 1dc86ab3a720
Removing intermediate container 1dc86ab3a720
 ---> b792b98b25d3
Step 5/18 : ENV LANG C.UTF-8
 ---> Running in 41daf634d8ce
Removing intermediate container 41daf634d8ce
 ---> fd154f41233b
Step 6/18 : COPY install.sh /
 ---> ba2063052a8d
Step 7/18 : RUN chmod a+x /install.sh
 ---> Running in 85d6080ab604
Removing intermediate container 85d6080ab604
 ---> e12e41730394
Step 8/18 : RUN /install.sh $BUILD_ARCH $TAILSCALE_VERSION
 ---> Running in b852ef673a4e
ARGS: armv7 1.8.5
Downloading tailscale 1.8.5 for armv7
ifconfig
eth0      Link encap:Ethernet  HWaddr 03:43:BC:11:00:03  
          inet addr:174.17.0.3  Bcast:174.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:910 (910.0 B)  TX bytes:306 (306.0 B)
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
dns
time.c:126: Operation not permitted
timer.c:617: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed

Aborted (core dumped)

Removing intermediate container b852ef673a4e

Thanks 
Sharath B K

**Comment by tsujamin** [comment]
Sorry I also forgot to ask what verison of HassOS/Supervisor/the underlying distro you're running. I'm just bringing my box up to latest to see if I can reproduce the issue.

Those second logs are super interesting because it shows the entire build process failing with a crash when I try and DNS resolve pkgs.tailscale.com. 
```
time.c:126: Operation not permitted
timer.c:617: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed
```

Having a quick google around I find https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=132872 and https://github.com/visibilityspots/dockerfile-cloudflared/issues/30 which seem related. In both cases there was an issue with the time being reported into the container subsequently breaking DNS... Can you double check the clock on your PI is being set correctly? Message #30 on the debian report may be useful, but honestly I'm grasping at straws here...

**Comment by sharathbk1912** [comment]
I did check time inside each container and also overall

![image](https://user-images.githubusercontent.com/79350776/127297871-6bcd9371-d4ea-4b10-82db-05aad1a54d5f.png)

However one thing i notice is that this supervisor container shows UTC

**Comment by tsujamin** [comment]
super interesting... I can't reproduce the issue but yeah its unlikely to be DNS specifically if it works in the other containers

I pushed another testing commit to https://github.com/tsujamin/tailscale-badaddr-test that hardcodes the domain name as a fallback. Want to give that a whirl and see if it builds and runs? If so I'll merge some fallback code into the main repo.

**Comment by sharathbk1912** [comment]
Hi Please find the log file with this test addon.

ipv4 shows failed however eth0 is 

21-08-05 12:13:03 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build eed28774/armv7-addon-tailscale:1.8.5.1: The command '/bin/ash -o pipefail -c /install.sh $BUILD_ARCH $TAILSCALE_VERSION' retur                                  ned a non-zero code: 1
21-08-05 12:13:03 ERROR (SyncWorker_3) [supervisor.docker.addon] Build log:
Step 1/18 : ARG BUILD_ARCH
Step 2/18 : FROM homeassistant/${BUILD_ARCH}-base:latest
 ---> 564b1f71f9e5
Step 3/18 : ARG BUILD_ARCH
 ---> Using cache
 ---> 2ee8490de1e9
Step 4/18 : ARG TAILSCALE_VERSION="1.8.3"
 ---> Using cache
 ---> b792b98b25d3
Step 5/18 : ENV LANG C.UTF-8
 ---> Using cache
 ---> fd154f41233b
Step 6/18 : COPY install.sh /
 ---> Using cache
 ---> c385603e2abf
Step 7/18 : RUN chmod a+x /install.sh
 ---> Using cache
 ---> de0e19bf7ee9
Step 8/18 : RUN /install.sh $BUILD_ARCH $TAILSCALE_VERSION
 ---> Running in 248f0f0fc262
ARGS: armv7 1.8.5
Downloading tailscale 1.8.5 for armv7
ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:03
          inet addr:172.17.0.3  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:910 (910.0 B)  TX bytes:196 (196.0 B)
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
  % Total    % Received %
 X
ferd  Average Spee
d   Time    T
ime     Time  Curre
nt




Dload  Upload   Tot
al   Spe
nt    Left  Spe
ed
  0

   0    0     0
  0     0      0      0 --:--
:-
- --:--:-- --:--:--     0
* Could not resolve host: ipv4.tlund.se

* Closing connection 0

curl: (6) Could not resolve host: ipv4.
tlund.se

ipv4 failed
ipv6
  % Total    % Received %
 Xferd  Average Speed   Time    Time     Time  Current

            Dload  Upload   Total   Spent    Lef
t  Speed
  0     0    0     0    0     0
    0
0

-
-:--:
-
-

-
-
:
-
-
:
-
-

-
-
:
-
-
:
-
-





0
*

Could not resolve host: ipv6.tlund.se

*

Closing connection 0

c
u
r
l
:

(
6
)

C
o
u
l
d

n
o
t

r
e
solve host: ipv6.tlund.se

ipv6 failed
dual
  % Total
 % Received % Xferd  Averag
e Speed   Time
Time     Time  Curren
t

                               Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0* Could not resolve host: dual.tlund.se

* Closing connection 0

curl: (6) Could n
ot res
olve host: dual.tl
und.se


dual failed
  % Total    %
 Received
% Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  U
pload   Total   Spent    Left  Speed
  0     0
  0     0    0     0      0      0 --:--:-- --:--:-- --
  0     0    0     0    0
0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (28) Failed to connect to pkgs.tailscale.com po
rt 443: Operation timed out

tar: invalid magic

tar: short read

Removing intermediate container 248f0f0fc262

**Comment by tsujamin** [comment]
So strange... it's as if there's no IP connectivity at all in the built container. I wonder if its just during build time (i.e. setting up some CICD to prebuild containers would fix it) or its a problem with docker.

Could you check 2 more things (sorry!):
  * `sysctl net.ipv4.ip_forward` from supervisor
  * `docker inspect de0e19bf7ee9` (or whatever the last layer before the one that fails to build is)
  * check connectivity between the last layer that didn't fail to build (de0e19bf7ee9)

**Comment by kusha** [comment]
Hi @tsujamin, I'm not sure if it is related to #11 or to this one, but I have a similar issue (supervised docker setup on amrv7 RPi 3b+). Sample logs:
```
Step 8/12 : RUN /install.sh $BUILD_ARCH $TAILSCALE_VERSION
 ---> Running in 893c375efb65
ARGS: armv7 1.12.3
Downloading tailscale 1.12.3 for armv7
Connecting to pkgs.tailscale.com (167.172.11.40:443)
ssl_client: pkgs.tailscale.com: certificate verification failed: format error in certificate's notBefore field
wget: error getting response: Connection reset by peer
tar: invalid magic
tar: short read
```
After adding `--no-check-certificate` attribute to `wget`:
```
Step 8/12 : RUN /install.sh $BUILD_ARCH $TAILSCALE_VERSION
 ---> Running in f93a3162f518
ARGS: armv7 1.12.3
Downloading tailscale 1.12.3 for armv7
Connecting to pkgs.tailscale.com (167.172.11.40:443)
writing to stdout
wget: clock_gettime(MONOTONIC) failed
tar: invalid magic
tar: short read
```
I forked the repo and switched the base image from Alpine to Debian: https://github.com/kusha/hass-addons-tailscale/commit/6f1f89f60745e128c79f2b1e74c071cb7e889042 
The installation worked w/o any issues, so I'm pretty sure it is Alpine specific...

**Comment by sharathbk1912** [comment]
This fork @kusha mentioned worked for me aswell

**Comment by tsujamin** [comment]
@kusha interesting, there must be some inconsistency between alpine's libc and the containerisation (based on the libc functions resulting in cordump in other crashes).

I'm going to pull your changes in and give it test now then might push a new release

**Comment by tsujamin** [comment]
1.12.3.2 released/rebased on debian (I cherry-picked your changes @kusha tyty) - does that alleviate the build issues?

**Comment by kusha** [comment]
@tsujamin I confirm that installation works form the upstream, ty

**Comment by tsujamin** [comment]
Awesome ty for writing it up and testing!
