### ISSUE TITLE
Losing connectivity to the Web GUI

### ISSUE THREAD

**Issue by kenmaina** [tsujamin/hass-addons#18]
Hello,
I'm losing connectivity to the GUI and can't ping HA a few moments after installing the addon. The machine still shows connected on Tailscale console.

My installation is:

Raspberry pi 3 b+ 64bit
Home Assistant OS 6.2
Core 2021.7.4
Supervisor-2021.06.8

**Comment by kenmaina** [comment]
Hello,
I'm losing connectivity to the GUI and can't ping HA a few moments after installing the addon. The machine still shows connected on Tailscale console. 

My installation is:

- Raspberry pi 3 b+ 64bit
- Home Assistant OS 6.2
- Core 2021.7.4
- Supervisor-2021.06.8

**Comment by tsujamin** [comment]
Hey mate - Sorry you're having the issue... is the machine accessible at all via the Tailscale 100.X address? Any notable settings in your addon config (exit node, advertised routes etc?)

I'll bring my HA up to 6.2 shortly and see if I can repro

**Comment by kenmaina** [comment]
@tsujamin The machine is reachable on 100.X addresses but the supervisor fails to start hence much of the GUI functionality is gone. I've also tried all combinations with no luck after formatting and starting afresh (with/without an exit node, removing all advertised routes etc.).

**Comment by tsujamin** [comment]
Very weird.... I've just added a userspace_networking option that you can enable so it shouldn't interfere with the underlying host as much... maybe give that a crack?

**Comment by kenmaina** [comment]
Yes that option helped. Thanks a lot. You do lose subnet route masquerading though.

**Comment by tsujamin** [comment]
No problem, sorry I'm not sure how to fix that issue at the moment sorry. Will close this for now but keep it in the back of my mind how we might do both :)
