### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by fredamn76** [tsujamin/hass-addons#19]
I'm using the latest version (1.12.1.0) of this addon. However Tailscale admin consle says its an old version of Tailscale. Can you update it?

**Comment by tsujamin** [comment]
Yeah sorry fell a couple if miner vers behind with work and stuff - will test and push an update shortly

**Comment by tsujamin** [comment]
v1.12.3.0 should be pushed now 👍

**Comment by fredamn76** [comment]
The new version is not avalible to me.
