### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by AJEvans3** [tsujamin/hass-addons#32]
Followed the guide and installed the addon, signed into Tailscale admin page, and everything looks good. Home Assistant is shown as green and connected but I cant connect to it at all. Web browser says "Cant establish a secure connection" or connection has been reset.

**Comment by tsujamin** [comment]
Hey mate. When you say you can't connect you mean to the home-assistant UI?

When you browse to it, are you using its tailscale IP and HTTP (no SSL?)), ala "http://100.X.X.X:8123/"?
