### ISSUE TITLE
I'm having trouble updating to the latest version 1.22.2.0

### ISSUE THREAD

**Issue by neildotwilliams** [tsujamin/hass-addons#35]
**Describe the bug**
You have 1.22.1.0 installed. Click update to update to version 1.22.2.0

I press the update button and get this:

The command '/bin/bash -o pipefail -c apt install -y wget iptables iproute2 procps' returned a non-zero code:100 

System info:
## System Health
version | core-2022.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 1010
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 219.4 GB
disk_used | 62.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (4.1.0), Mosquitto broker (6.0.1), Grafana (7.5.0), InfluxDB (4.4.0), Node-RED (11.1.0), Terminal & SSH (9.3.0), Glances (0.15.0), Tailscale (1.22.1.0), ArgonOne Active Cooling (24.1), Samba share (9.5.1), Check Home Assistant configuration (3.10.0), Home Assistant Google Drive Backup (0.105.2), Portainer (2.0.0), Zigbee2mqtt (1.23.0-1), Duck DNS (1.14.0), Frigate NVR (Full Access) (3.1), Double Take (1.7.0), TasmoAdmin (0.17.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 10
views | 15
mode | storage

</details>

**Comment by tsujamin** [comment]
Hey mate - someone had the same issue with 1.21.1.0 (https://github.com/tsujamin/hass-addons/issues/34) which disappeared when 1.21.2.0 came out, making me think its some debian-repos-not-being-in-sync issue while the container was building...

I don't really have a fix for it at the moment short of waiting for the next minor version bump, sorry!

**Comment by tsujamin** [comment]
lmk if you're all good and I'll close this? :)

**Comment by neildotwilliams** [comment]
All good now thanks 🙏

**Comment by tsujamin** [comment]
np have a good night and sorry about the inconvenience!
