### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1 after the update to 1.24.2.0 

### ISSUE THREAD

**Issue by AaronPower** [tsujamin/hass-addons#39]
Subject says it all. Got the error after updating. Client doesn't connect.

## System Health

version | core-2022.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Prague

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.11.1
Stage | startup
Available Repositories | 880
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.1
docker_version | 20.10.9
disk_total | 28.6 GB
disk_used | 12.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Terminal & SSH (9.3.0), WireGuard (0.5.1), Grafana (7.5.0), InfluxDB (4.4.0), Mosquitto broker (6.0.1), Duck DNS (1.14.0), NGINX Home Assistant SSL proxy (3.1.1), MariaDB (2.4.0), Samba Backup (5.0.0), ESPHome (2022.3.0), Check Home Assistant configuration (3.9.0), Zigbee2mqtt (1.24.0-1), File editor (5.3.3), Tailscale (1.24.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 8
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by tsujamin** [comment]
Think its fixed now, "Check for update" in your addons page and let me know if the new build works for you? :)
