### ISSUE TITLE
Update from 1.26.1.0 to 1.26.2.0 fails

### ISSUE THREAD

**Issue by ovizii** [tsujamin/hass-addons#44]
**Describe the bug**
Update from 1.26.1.0 to 1.26.2.0 fails via HA => Addons update.

**To Reproduce**
1. Go to settings
2. Click on Add-ons
3. Click on Taislcale
4. Click on Update
5. See error below

**Expected behavior**

**Desktop (please complete the following information):**
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.06.2
Home Assistant OS 8.2

**Additional context**
`The command '/bin/bash -o pipefail -c /install.sh $BUILD_ARCH $TAILSCALE_VERSION' returned a non-zero code: 2`

![image](https://user-images.githubusercontent.com/837902/177541223-4ee08fee-e672-478a-81af-3e7e75099566.png)

**Comment by tsujamin** [comment]
Ah looks like they rolled back the 1.26.2 binaries

give me 5 and I'll roll back the last changes and version bump

**Comment by tsujamin** [comment]
refresh your addons and try installing `1.26.2.1` - should work for now
<img width="698" alt="image" src="https://user-images.githubusercontent.com/2435619/177542687-3bafe9d2-9c12-41f3-a44b-8c691c0723bb.png">

**Comment by ovizii** [comment]
Thanks, you're the best ;-)
