### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by feron81** [tsujamin/hass-addons#48]
I would like to install the add-on on a docker container. I don‘t have „supervisor“. Can I install „supervisor“ or the „add-on“ manually?

**Comment by tsujamin** [comment]
Hey mate. Unfortunately not with this add on, as it's a community maintained plugin specifically for HomeAssistant with its internal Supervisor.

Your best bet would probably be using Tailscale's own @docker container (https://hub.docker.com/r/tailscale/tailscale) or referring to their own guidance on docker/Userspace networking (https://tailscale.com/kb/1112/userspace-networking/)
