### ISSUE TITLE
Unable to install addon

### ISSUE THREAD

**Issue by aaddame** [tsujamin/hass-addons#55]
**Describe the bug**
Trying to install on hassio addons i get the following error msg:
The command '/bin/bash -o pipefail -c apt install -y wget iptables iproute2 procps' returned a non-zero code: 100 

**To Reproduce**

**Expected behavior**
An install without error msg

**Desktop (please complete the following information):**
 - Plugin Version: [1.32.3
 - Home Assistant/Supervisor Versions:  2022.11.4/2022.11.2 
**Additional context**

**Comment by tsujamin** [comment]
Hey mate. Not sure what had caused the issue as I'm still able to build the current container.

Similar issues have been reported periodically which have alleviated themselves after a few days, so I'm guessing it's to do with the Debian mirror nearest you being out of sync.

Is it still not building?

**Comment by aaddame** [comment]
still not

**Comment by aaddame** [comment]
Anything on this?

**Comment by tsujamin** [comment]
Nah sorry mate cant reproduce, does it occur in the other HA Tailscale addon? Sorry

**Comment by aaddame** [comment]
solved it. It was a dns issue
