### ISSUE TITLE
Subnets not working

### ISSUE THREAD

**Issue by magic2910** [tsujamin/hass-addons#61]
Unfortunately the subnets not working for me.
Neither the local subnet nor the routed one (via udm pro)
I have only access to the HA via Tailscale.

advertised routes:
192.168.178.0/24,172.16.0.0/23

what I am doing wrong?

I also get ok in the Log:

023/01/07 14:24:25 Accept: TCP{100.xxx.xxx.85:57885 > 172.16.0.9:80} 64 tcp ok

**Comment by tsujamin** [comment]
Strange, have you tried enabling userspace networking in the addon settings?

**Comment by magic2910** [comment]
Thanks! Now it is working.
Sorry for the circumstances

**Comment by tsujamin** [comment]
All good! Common issue, I should just make it the default :)

**Comment by chriscn** [comment]
Sorry for necroposting, I was just about to ask for help with the same issue. 

@tsujamin I'd agree in making it on by default or at least on when you specify subnet routes.

**Comment by tsujamin** [comment]
I'll try hack that in next I'm in the codebase, need to work out how to grandfather existing configs etc 👍👍
