### ISSUE TITLE
Cannot install on raspberry pi 4

### ISSUE THREAD

**Issue by ChrisKolan** [tsujamin/hass-addons#70]
After pressing the install button I get this error:

"Failed to to call /addons/948e3081_tailscale/install - The command '/bin/bash -o pipefail -c apt update' returned a non-zero code: 100
22:48:43 – (ERROR) Home Assistant Supervisor - message first occurred at 22:18:01 and shows up 5 times"

Could it be because I have an outdated version of home assistant?

**Desktop (please complete the following information):**
 - Plugin Version: 1.36.2.0
 - Home Assistant/Supervisor Versions: core-2022.11.4/supervisor-2023.01.1

**Comment by tsujamin** [comment]
Hey mate

Don't think so, tends to be due to a temporary network issue your end or your nearest Debian mirror being out of sync. There was an issue I closed out recently with a similar issue it might be worth checking (can't check which atm sorry)

Alternatively give it a few days and try again 😁

**Comment by tsujamin** [comment]
Any change/improvement?

**Comment by ChrisKolan** [comment]
@tsujamin Yes, I used different machine and I was able to install the addon.
