### ISSUE TITLE
Add on failure message after restart of  the addon

### ISSUE THREAD

**Issue by Aaroneisele55** [tsujamin/hass-addons#78]
**Describe the bug**
When I restart the add-on, I get a "Restart failed" message from Home Assistant
**To Reproduce**
I don't know how to reproduce it, for me, it happens anytime

**Expected behavior**
I shouldn't get the error message

**Desktop (please complete the following information):**
 - Plugin Version: 
 - Home Assistant/Supervisor Versions:

**Additional context**
In my logs, there is the following line:
````
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
````

**Comment by tsujamin** [comment]
hey, sorry you're having the issue 😢 

Just as background, was the addon working fine before? Are there any log lines prior to this that appear to successfully/unsucesfully open a file under `/var/lib/tailscale`?

**Comment by Aaroneisele55** [comment]
Yes, it did work fine previously
These lines were the first in the log

**Comment by tsujamin** [comment]
Sorry mate think the log lines might be missing
