### ISSUE TITLE
Can't find tailscale binary when logged into hassio via ssh

### ISSUE THREAD

**Issue by jackmac92** [tsujamin/hass-addons#8]
**Describe the bug**
Sorry this might be a dumb issue, but I was surprised that `tailscale` wasn't in PATH post install. It looks like the script moves it to `/bin`, but I couldn't find it there. Do you know why I can't find it? 

**Additional context**
Protection mode is off for the ssh/web terminal add-on

**Comment by tsujamin** [comment]
Hey mate - Just checking, do you mean the PATH of your SSH/Web terminal addon, or within the Tailscale container?

Since the plugin runs in its own container, you may need to use your ssh/web terminal addon to identify the container hash then exec `tailscale` within that container. e.g.

```bash
➜  ~ docker ps | grep tailscale
8aa5af6af948   local/armhf-addon-tailscale:1.6.0.1                "/init /run.sh"          2 weeks ago   Up 2 weeks                          addon_local_tailscale
➜  ~ docker exec 8aa5af6af948 tailscale
USAGE
  tailscale [flags] <subcommand> [command flags]

For help on subcommands, add -help after: "tailscale status -help".
```

Let me know if this works for you, or if I've misunderstood something 😄

**Comment by jackmac92** [comment]
Oh right my misunderstanding, forgot everything is now running in its own container.
I'm looking for a way to [specify an exit node](https://tailscale.com/kb/1103/exit-nodes#:~:text=Step%203%3A%20Use%20the%20exit%20node) would you accept a PR which adds that as a configuration option?

**Comment by tsujamin** [comment]
That sounds like a great feature, would definitely appreciate a PR! If you can just doubly make sure to update the configuration docs that would be appreciated (I’ll do changelog/version bump when I merge it 👍)

On 17 Apr 2021, at 3:28 pm, Jack McCown ***@***.***> wrote:

﻿

Oh right my misunderstanding, forgot everything is now running in its own container.
I'm looking for a way to specify an exit node<https://tailscale.com/kb/1103/exit-nodes#:~:text=Step%203%3A%20Use%20the%20exit%20node> would you accept a PR which adds that as a configuration option?

**Comment by alamoudimoh** [comment]
> Oh right my misunderstanding, forgot everything is now running in its own container. I'm looking for a way to [specify an exit node](https://tailscale.com/kb/1103/exit-nodes#:~:text=Step%203%3A%20Use%20the%20exit%20node) would you accept a PR which adds that as a configuration option?

Hi Jack,

let me just confirm my understanding of this, so specify an exit node meaning, do not communication from HA will go to my computer (foe example) and from there it will see its way to the internet? or the other way around, which make HA as an exit node taking all the traffic to the internet.


if you could please take a look and let me know: https://github.com/tsujamin/hass-addons/issues/40#issuecomment-1133582398

**Comment by jackmac92** [comment]
Hey @alamoudimoh I actually don't use this config option for HA currently, so I can't help too much

But the exit node is the server which the rest of the internet will see as the originator of the request.

Maybe you need to setup the exit node server you want as an exit node?
