### ISSUE TITLE
Add options for --socks5-server and --outbound-http-proxy-listen

### ISSUE THREAD

**Issue by Mincka** [tsujamin/hass-addons#81]
**Is your feature request related to a problem? Please describe.**
SOCKS5 and HTTP proxies can be used when --tun=userspace-networking is used.
It can be useful when you want other containers to route their traffic through the tailscale add-on.

In my case, I have a Firefox container that cannot reach other tailscale nodes.
I set the tailscale's SOCKS5 proxy in Firefox and then I can reach the other nodes of the network.

**Describe the solution you'd like**
Add support for flags `--socks5-server` and `--outbound-http-proxy-listen`

Command example:
`tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055`

**Describe alternatives you've considered**
Unknown

**Additional context**
Documation:
https://tailscale.com/kb/1112/userspace-networking/#socks5-vs-http

**Comment by tsujamin** [comment]
Hey mate - happy to merge in such a change but my life is a bit too busy to implement them myself at the moment.

If you want to have a crack it and make a pull request it should be pretty easy to get it implemented. Roughly:

add new configuration keys to the addon settings: https://github.com/tsujamin/hass-addons/blob/9f8bcb8ac3ec480179d9536d30fef2f7c2b390c3/tailscale/config.json#L30-L46

Read the new configuration keys and, if present, append to the tailscaled arguments similar to https://github.com/tsujamin/hass-addons/blob/9f8bcb8ac3ec480179d9536d30fef2f7c2b390c3/tailscale/run.sh#L66-L68

**Comment by tsujamin** [comment]
Awesome 👏 raise the PR when it suits you and I'll merge and push a new release

Thanks!

**Comment by bslatyer** [comment]
Hey @Mincka,

Is this still being worked on?

Thanks,

Braeden
