### ISSUE TITLE
site-to-site networking is not working due to userspace-networking enabled

### ISSUE THREAD

**Issue by Gyosa3** [tsujamin/hass-addons#84]
**Describe the bug**
Hi, I'm trying to setup a site-to-site tunnel using Tailscale and the proper routing of non-tailscale machines via the addon requires that `userspace-networking` option is disabled, so that the interface `tailscale0 `is visible and part of the routing tables on the HAOS host.
However this addon only works with announced routes if this option is enabled, so devices in the tailscale network can access non-tailscale devices locally, but local non-tailscale devices cannot access remote devices via tailscale.

**To Reproduce**
1. Install the addon on a local HA and on a remote HA instances > OK
2. Announce a local route on both addons, e.g. `192.1668.2.0/24` on one side and `192.168.3.0/24` on the other side > OK
3. create a static route on the local routers on each side to route remote IPs to the local HA nodes > OK 
4. with a device outside of both local LANs that has tailscale installed, access a non-tailscale device on both announced lans > OK
5. with a non-tailscale device located on one announced LAN, try to reach another device located on the other announced lan > FAIL

**Expected behavior**
I am trying to implement site-to-site networking according to https://tailscale.com/kb/1214/site-to-site/
We had a previous chat here about the `userspace-networking` option and I tested and confirm that the announced routes were not reachable with this option was disabled. However, after having other talks with the owner of this addon: https://github.com/lmagyar/homeassistant-addon-tailscale
He managed to have site-to-site working without having this option enabled, by adding extra lines in routing tables and a few other things that escape me... (I'm not a network engineer...) The limitation of his addon however is that I cannot advertise routes other than the LAN where HA is. This is to stay in line with the spirit of the HA team not wanting to manage networks that are not managed by the HA supervisor.

Bottom line is, I'd need the option of your addon to advertise extra routes, together with the option on his addon to have routing working without `userspace-networking` enabled. If you need I can send a snapshot of the routes that are declared by his addon to see the difference with yours when `userspace-networking` is disabled (and `tailscale0 `interface exists instead).

**Desktop (please complete the following information):**
 - Plugin Version: latest
 - Home Assistant/Supervisor Versions: latest

**Additional context**
Today I'm running your addon on one site and the other addon on the other site and I have tested that with the other addon, a non-tailscale machine can well access the remote devices on all the routes announced by your addon. But it only works one way, so I'm seeking to make it work both ways.

**Comment by tsujamin** [comment]
Hey mate - I think issues like this have come up before in this addon and I’ve not really been able to identify a workable solution. I think this is where the limitations of running Tailscale within the boundaries of a Home Assistant container start to bite unfortunately, you might be better off running your node outside of the addon/container

Ill have a bit more of a think on it but I can’t say I’ll be able to commit to a fix at the moment sorry

**Comment by Gyosa3** [comment]
I understand, no prob. 

My understanding: To use the node for site-to-site the `userspace-networking` option has to be disabled, so that a new interface `tailscale0` exists and can be associated some extra routes for the local and remote lans. And I think the issue is that there must be a special binding between `eth0` and `tailscale0` to forward the packets correctly. Something that is missing in your addon that lmagyar added in his beta version successfully.

I'll try to read his code again and tell you if I can find a silver bullet in there.

**Comment by tsujamin** [comment]
It could be to do with Home Assistant’s firewall rules, or potentially that ‘net.ipv4.ip_forward=1’ isn’t being set as a sysctl properly but yeah it’s hard to say, sorry!

**Comment by lmagyar** [comment]
FYI:
- the above mentioned iptables manipulation is for clamping the MSS to the MTU (based on Tailscale's documentation), even without this, the forwarding should work, so the problem should be somewhere else I think
- I didn't managed to make site-to-site working without userspace-networking:
  - subnet routing on **destination** side is independent of userspace networking: this is about the **incoming** traffic (tailnet->lan) on the destination side
  - subnet routing on **source** side requires non userspace networking, ie. to have tailscale0, to be able to route **outgoing** traffic (lan->tailnet) on the source side
- based on this add-on's run.sh, configuring userspace networking and advertising subnets are independent, so I ***think*** this can't be true: "this addon only works with announced routes if this option is enabled", so I ***think*** this issue is a mis-configuration
