### ISSUE TITLE
Add-on doesn't install

### ISSUE THREAD

**Issue by Aaroneisele55** [tsujamin/hass-addons#91]
**Describe the bug**
The add-on doesn't install, the error message is "Image 948e3081/aarch64-addon-tailscale:1.48.1.0 does not exist for addon_948e3081_tailscale"

**To Reproduce**
Try to install the add-on on a raspberry pi 4 with HA OS

**Expected behavior**
The add-on should be installed

**Desktop (please complete the following information):**
 - Plugin Version: latest
 - Home Assistant/Supervisor Versions: latest

**Comment by Aaroneisele55** [comment]
Solved, I judt had to push the rebuild ("neu bauen" in my german HA instance) button on the addon settings page

**Comment by tsujamin** [comment]
Hi mate - sorry I didn't respond, busy period currently. Glad that rebuilding the addon worked succesfully! I've added a note to this effect to the readme and issue tempalte to help future users.
