### ISSUE TITLE
Unable to install new update to 1.50

### ISSUE THREAD

**Issue by johnwalk61** [tsujamin/hass-addons#95]
I tried removing then I get the following error when reinstalling...

Head "https://registry-1.docker.io/v2/homeassistant/amd64-base-debian/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Famd64-base-debian%3Apull&service=registry.docker.io": read tcp 192.168.68.XXX:44028->18.215.138.58:443: read: connection reset by peer

Thanks

**Comment by tsujamin** [comment]
Good to hear! That won't have been an issue with the addon-specifically, but some underlying network issue in HA. Best bet if it happens again would be to disable the addon, reboot then update just to be sure that Tailscale hasn't broken your networking temporarily :)
